# Generated by Django 4.2.15 on 2024-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekolah', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('tahun_masuk', models.IntegerField()),
                ('tahun_lulus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PengalamanKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
