# Generated by Django 4.2.15 on 2024-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=255)),
                ('no_ktp', models.CharField(max_length=16)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
