# Generated by Django 4.2.15 on 2024-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata_app', '0002_user'),
    ]

    operations = [
    ]
