# Generated by Django 4.2.15 on 2024-08-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata_app', '0003_auto_20240812_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendidikan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pendidikan', to='biodata_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengalamankerja',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pengalaman_kerja', to='biodata_app.user'),
            preserve_default=False,
        ),
    ]
